# Generated by Django 5.0.1 on 2024-06-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
