# Generated by Django 5.0.1 on 2024-09-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_bought_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
