# Generated by Django 5.0.1 on 2024-10-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_category_phone_category_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtitems',
            name='status',
        ),
        migrations.AddField(
            model_name='bought',
            name='Bought_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bought',
            name='payment',
            field=models.CharField(choices=[('cod', 'cod'), ('online', 'online')], default='cod', max_length=200),
        ),
        migrations.AddField(
            model_name='bought',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('intransit', 'intransit'), ('dispatched', 'dispatched'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='order-placed', max_length=200),
        ),
    ]
